# Game constants
GRID_SIZE = 50
GRID_WIDTH = 16
GRID_HEIGHT = 12
SCREEN_WIDTH = GRID_SIZE * GRID_WIDTH
SCREEN_HEIGHT = GRID_SIZE * GRID_HEIGHT
FROG_SIZE = GRID_SIZE

# Colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)